name = "Kita"
description = "Kita is a clean, elegant and simple blog theme for Zola."
license = "MIT"
homepage = "https://github.com/nulltux/kita-farsi"
min_version = "0.17.0"
demo = "https://nulltux.ir/"

[author]
name = "daradege"
homepage = "https://nulltux.ir"

[original]
author = "st1020"
homepage = "https://st1020.com/"
repo = "https://github.com/st1020"